<ul style="list-style-type:circle;font-size:14px;line-height:27px;">
    <li><b>from streamanalytix.python.dataset import Dataset:</b> Load Dataset class from streamanalytix API.</li>
	<li><b>Dataset(source_name):</b> Creates object of dataset class for given source.
		<ul>
			<li><b>Dataset.get_dataframe():</b> Read data source and return a pandas dataframe. </li>
		</ul>
	</li>
	<li><b>from streamanalytix.utilities import sax_utils:</b> Load sax_util script. It has following functions
		<ul>
			<li><b>sax_utils.save_and_download_model(model_name, model_object):</b>This method lets the user to save and download the trained model with StreamAnalytix. This model can than be used for training and/or scoring purpose as part of the StreamAnalytix pipeline</li>
				<ul>
					<li><b>model_name:</b> Name of the model. Accepted String value only. e.g. <i>"DecisionTreeModel"</i></li>
					<li><b>model_object:</b> Object of the trained model</li>
				</ul>
			<li><b>sax_utils.create_h2o_frame(source_name, cluster_name):</b>This method read data source and return H2O frame using notebook environment.</li>
				<ul>
					<li><b>source_name:</b> Name of the source. Accepted String value only. e.g. <i>"MyDataSource"</i></li>
					<li><b>cluster_name:</b> Name of the cluster. Accepted String value only. e.g. <i>"TrainingCluster"</i></li>
				</ul>
			<li><b>sax_utils.upload_and_register_h2o_model(model_object, model_name, model_type, project_name, project_version, workspace_name):</b>This method lets the user to upload and register h2o model in 'mojo' format in streamanalytix</li>
				<ul>
					<li><b>model_object:</b> Object of trained H2O model</li>
					<li><b>model_name:</b>Name of the model. Accepted String value only. e.g. <i>"H2OTreeModel"</i>
					<li><b>model_type:</b>Type of trained model. Accepted String value only. We support H2O model of types :<i>"DistributedRandomForest"</i>,<i>"GeneralizedLinearModelling"</i>,<i>"IsolationForest"</i>,<i>"GradientBoostingMachine"</i></li>
					<li><b>project_name:</b>Project Name in which model should register. Accepted String value only. e.g. <i>"MyProject"</i></li>
					<li><b>project_version:</b>Version of given project in which model should register</li>
					<li><b>workspace_name:</b>Workspace Name in which model should register. Accepted String value only. e.g. <i>"MyWorkspace"</i></li>
				</ul>
		</ul>
	</li>
</ul>

In [1]:
from streamanalytix.python.dataset import Dataset
from streamanalytix.utilities import sax_utils


dataset_1 = Dataset("PythonNotebookGitHub27")

# you can use pandas to create dataframe as shown below
df = dataset_1.get_dataframe()

/usr/lib/python2.7/site-packages/urllib3/connection.py:394: SubjectAltNameWarning: Certificate for impetus-i0141.impetus.co.in has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/urllib3/urllib3/issues/497 for details.)
  SubjectAltNameWarning,

Dataframe created

/usr/lib/python2.7/site-packages/urllib3/connection.py:394: SubjectAltNameWarning: Certificate for impetus-i0319.impetus.co.in has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/urllib3/urllib3/issues/497 for details.)
  SubjectAltNameWarning,

In [3]:
df.head(7)

,time_of_day,raining,accident_prone_area,g_force,n_prev_instances,risky,event_id,driver_id,start_latitude,start_longitude,...,hard_accels,duration_over_70_s,duration_over_75_s,duration_over_80_s,start_timezone,end_timezone,city_fraction,highway_fraction,idling_time_s,tags
0,night,True,True,3.655726,2,high,290006,239667.0,33.991567,-118.373910,...,1,0,0,0,America/Los Angeles,America/Los Angeles,1,0,23,personal
1,night,True,True,2.504833,2,high,266909,280747.0,34.005797,-118.380589,...,0,0,0,2,America/Los Angeles,America/Los Angeles,1,0,51,business
2,night,True,False,2.395466,4,high,240268,210003.0,33.985797,-118.367131,...,0,0,0,0,America/Los Angeles,America/Los Angeles,1,0,62,business
3,night,True,True,2.499510,4,high,254616,274993.0,34.066769,-118.378835,...,0,2,0,0,America/Los Angeles,America/Los Angeles,1,0,18,business
4,night,True,True,3.445432,1,high,281953,244457.0,34.030714,-118.384605,...,0,0,0,0,America/Los Angeles,America/Los Angeles,1,0,11,business
5,night,True,True,2.463138,4,high,297413,211041.0,34.048773,-118.366689,...,0,0,0,0,America/Los Angeles,America/Los Angeles,1,0,43,personal
6,night,True,True,0.725256,1,high,296443,231118.0,34.050272,-118.380269,...,0,0,0,0,America/Los Angeles,America/Los Angeles,1,0,28,business